name: satory
 
# ======================================================================
# NETWORKS
# ======================================================================
networks:
  satory_net:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: satory0

  back-tier:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: backend0

services:

  librenms-db:
    image: mariadb:10
    container_name: librenms-db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      - "TZ=${TZ}"
      - "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${LNMS_DATABASE}"
      - "MYSQL_USER=${LNMS_USER}"
      - "MYSQL_PASSWORD=${LNMS_PASSWORD}"
    volumes:
      - "./db/mysql/librenms:/var/lib/mysql"
    restart: always
    networks:
      - back-tier

  phpipam-db:
    image: mariadb:10
    container_name: phpipam-db
    command:
      - "mysqld"
      - "--innodb-file-per-table=1"
      - "--lower-case-table-names=1"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    environment:
      - "TZ=${TZ}"
      - "MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}"
      - "MYSQL_DATABASE=${PHPIPAM_DATABASE}"
      - "MYSQL_USER=${PHPIPAM_USER}"
      - "MYSQL_PASSWORD=${PHPIPAM_PASSWORD}"
    volumes:
      - "./db/mysql/phpipam:/var/lib/mysql"
    restart: always
    networks:
      - back-tier

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
    environment:
      - "TZ=${TZ}"
    networks:
      - back-tier

  redis:
    image: redis:7.2-alpine
    container_name: redis
    environment:
      - "TZ=${TZ}"
    restart: always
    networks:
      - back-tier

  msmtpd:
    image: crazymax/msmtpd:latest
    container_name: msmtpd
    env_file:
      - "./msmtpd/.env"
    restart: always
    networks:
      - back-tier

  librenms-web:
    image: librenms/librenms:latest
    container_name: librenms-web
    hostname: librenms-web
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms-db
      - redis
      - msmtpd
    volumes:
      - "./db/librenms:/data"
    env_file:
      - "./librenms/librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=librenms-db"
      - "DB_NAME=${LNMS_DATABASE}"
      - "DB_USER=${LNMS_USER}"
      - "DB_PASSWORD=${LNMS_PASSWORD}"
      - "DB_TIMEOUT=60"
    restart: always
    networks:
      - back-tier
      - satory_net

  librenms-dispatcher:
    image: librenms/librenms:latest
    container_name: librenms-dispatcher
    hostname: librenms-dispatcher
    cap_add:
      - NET_ADMIN
      - NET_RAW
    depends_on:
      - librenms-web
      - redis
    volumes:
      - "./db/librenms:/data"
    env_file:
      - "./librenms/librenms.env"
    environment:
      - "TZ=${TZ}"
      - "PUID=${PUID}"
      - "PGID=${PGID}"
      - "DB_HOST=librenms-db"
      - "DB_NAME=${LNMS_DATABASE}"
      - "DB_USER=${LNMS_USER}"
      - "DB_PASSWORD=${LNMS_PASSWORD}"
      - "DB_TIMEOUT=60"
      - "DISPATCHER_NODE_ID=dispatcher1"
      - "SIDECAR_DISPATCHER=1"
    restart: always
    networks:
      - back-tier
      - satory_net
      # --------------------------------------------------------------------

  phpipam-web:
      image: phpipam/phpipam-www:latest
      container_name: phpipam-web
      environment:
        - TZ=Asia/Almaty
        - IPAM_DATABASE_HOST=phpipam-db
        - IPAM_DATABASE_PASS=${PHPIPAM_PASSWORD}
        - IPAM_DATABASE_WEBHOST=%
      restart: unless-stopped
      volumes:
        - phpipam-logo:/phpipam/css/images/logo
        - phpipam-ca:/usr/local/share/ca-certificates:ro
      networks:
      - back-tier
      - satory_net
      depends_on:
        - phpipam-db
      cap_add:
        - NET_ADMIN
        - NET_RAW

  phpipam-cron:
      image: phpipam/phpipam-cron:latest
      container_name: phpipam-cron
      environment:
        - TZ=Asia/Almaty
        - IPAM_DATABASE_HOST=phpipam-db
        - IPAM_DATABASE_PASS=${PHPIPAM_PASSWORD}ls
        - SCAN_INTERVAL=1h
      restart: unless-stopped
      volumes:
        - phpipam-ca:/usr/local/share/ca-certificates:ro
      networks:
        - back-tier
      depends_on:
        - phpipam-db
      cap_add:
        - NET_ADMIN
        - NET_RAW

  oxidized:
    image: docker.io/oxidized/oxidized:latest
    container_name: oxidized
    restart: always
    networks:
      - back-tier
    ports:
      - "8888:8888"
    environment:
      CONFIG_RELOAD_INTERVAL: 86400
    volumes:
      - ./oxidized-config:/home/oxidized/.config/oxidized

  
  # GRAFANA
  # --------------------------------------------------------------------
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    restart: unless-stopped
    user: "0:0"

    networks:
      - back-tier
      - satory_net
    environment:
      - TZ=Asia/Almaty
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=StrongGrafanaPass
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=https://grafana.satory.kz/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./db/grafana:/var/lib/grafana
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/login"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  # --------------------------------------------------------------------
  # PROMETHEUS
  # --------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    networks:
      - back-tier
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./db/prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 5

  # --------------------------------------------------------------------
  # SNMP EXPORTER
  # --------------------------------------------------------------------
  snmp-exporter:
    image: prom/snmp-exporter:latest
    container_name: snmp-exporter
    restart: unless-stopped
    ports:
      - 9116:9116
    networks:
      - back-tier
    volumes:
      - ./prometheus/snmp.yml:/etc/snmp_exporter/snmp.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9116/metrics"]
      interval: 30s
      timeout: 10s
      retries: 5

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped
    ports:
      - "3100:3100"  # HTTP API для Grafana
    networks:
      - back-tier
    volumes:
      - ./db/loki:/loki
    command:
      - "-config.file=/etc/loki/local-config.yaml"

  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    restart: unless-stopped
    networks:
      - back-tier
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log:ro
      - ./promtail/config.yml:/etc/promtail/config.yml:ro
    command:
      - "-config.file=/etc/promtail/config.yml"

# --------------------------------------------------------------------
  # MONGODB (Graylog metadata)
  # --------------------------------------------------------------------
  mongodb:
    image: mongo:6
    container_name: graylog-mongo
    restart: unless-stopped
    networks:
      - back-tier
    volumes:
      - ./db/mongo:/data/db
    environment:
      - TZ=Asia/Almaty

  # --------------------------------------------------------------------
  # OPENSEARCH (Graylog storage)
  # --------------------------------------------------------------------
  opensearch:
    image: opensearchproject/opensearch:2
    container_name: graylog-opensearch
    restart: unless-stopped
    networks:
      - back-tier
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - ./db/opensearch:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  # --------------------------------------------------------------------
  # GRAYLOG
  # --------------------------------------------------------------------
  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    restart: unless-stopped
    depends_on:
      - mongodb
      - opensearch
    networks:
      - back-tier
      - satory_net
    ports:
      - "9000:9000"   # Web UI
      - "1514:1514/udp" # Syslog
      - "12201:12201/udp" # GELF
    environment:
      - TZ=Asia/Almaty

      # пароль admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=d54c3472c4b97c51c093577a16ea37b9870c85b303698f505fd0caf1c5b74993

      # секрет
      - GRAYLOG_PASSWORD_SECRET=someverylongrandomstring

      # backend
      - GRAYLOG_MONGODB_URI=mongodb://mongodb:27017/graylog
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200

      # веб
      - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog.satory.kz/
    volumes:
      - graylog_data:/usr/share/graylog/data


  nginx:
    image: nginx:1.25-alpine
    container_name: satory-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - satory_net
      - back-tier     # <-- ДОБАВИТЬ

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./db/nginx/logs:/var/log/nginx
    environment:
      - "TZ=${TZ}"
    depends_on:
      - librenms-web
      - phpipam-web
      - grafana
      - oxidized
  

volumes:
  phpipam-logo:
  phpipam-ca:
  loki-data:
  oxidized_data:
  graylog_data: