input {
  udp {
    port => 5140
    type => "syslog"
  }

  tcp {
    port => 5140
    type => "syslog"
  }
}

filter {
  if [type] == "syslog" {
    grok {
      match => {
        "message" => [
          "<%{POSINT:syslog_pri}>%{SYSLOGLINE}",
          "%{SYSLOGLINE}"
        ]
      }
      tag_on_failure => ["_grok_syslog_failure"]
    }

    syslog_pri { }

    mutate {
      add_field => { "event.dataset" => "syslog.generic" }
      add_field => { "observer.type" => "logstash" }
    }

    date {
      match => [ "timestamp", "MMM  d HH:mm:ss", "MMM dd HH:mm:ss", "ISO8601" ]
      target => "@timestamp"
    }

    if [host] and ![source][ip] {
      mutate {
        rename => { "host" => "[source][ip]" }
      }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "syslog-%{+YYYY.MM.dd}"
  }

  stdout {
    codec => rubydebug
  }
}