
# --------------------------------------------------------------------
# GRAFANA
# --------------------------------------------------------------------

server {
    listen 80;
    server_name grafana.satory.kz grafana;

    # Docker embedded DNS
    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 2s;

    location / {
        set $up grafana:3000;

        proxy_pass http://$up;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # если бэкенд не резолвится/не доступен — не "сыпем" в логах бесконечно
        proxy_connect_timeout 2s;
        proxy_read_timeout 30s;

        proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}


# ----------------------------------------
# OBSERVIUM
# ----------------------------------------
server {
    listen 80;
    server_name observium.satory.kz librenms-web;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 2s;

    location / {
        set $up librenms-web:8000;
        proxy_pass http://$up;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout 2s;
        proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}


# ----------------------------------------
# PHPIPAM
# ----------------------------------------
server {
    listen 80;
    server_name ipam.satory.kz phpipam-web;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 2s;

    location / {
        set $up phpipam-web:80;
        proxy_pass http://$up;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        proxy_connect_timeout 2s;
        proxy_next_upstream error timeout invalid_header http_502 http_503 http_504;
        proxy_next_upstream_tries 2;
    }
}

# ----------------------------------------
# OXIDIZED
# ----------------------------------------
server {
    listen 80;
    server_name oxidized.satory.kz oxidized;

    resolver 127.0.0.11 valid=10s ipv6=off;
    resolver_timeout 2s;

    location / {
        proxy_pass http://oxidized:8888;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 2s;
        proxy_read_timeout 30s;
    }
}


